trigger:
  - main

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo $(sv)  # Use the secret variable in a script step
            displayName: Echo secret variable

          # Add more steps as needed
