trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true


- script: |
    az account show
   
  displayName: 'Install Terraform'


- script: |
    echo "Application deployed!"
  displayName: 'Post-build'
