trigger:
  - main

variables:
  secretVariable: $(mySecretVariable)  # Reference the secret variable using the $(variableName) syntax

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo $(secretVariable)  # Use the secret variable in a script step
            displayName: Echo secret variable

          # Add more steps as needed
