version: "3"
services:
  central:
    build:
      dockerfile: ./central/Dockerfile
    ports:
      - 5006:5006
    volumes:
      - xai_fw_volumes:/central/central_storage
volumes:
  xai_fw_volumes:
